version: '2'
services:
  rapid-admin:
    image: caterpillar/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  rapid-api:
    image: caterpillar/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev